[path]
# Path to Trackmate csv, all output will be stored in that folder
csv_path = ""
# Path to segmented masks, .png and .txt files required from Cellpose
mask_path = ""

[track-sorting]
allowed_gap_max = 20
allowed_track_length_min = 50
allowed_track_length_max = 1500
dist_range = 5
allowed_overlap = 30

[bound-classification]
distance_threshold = 3.0
distance_threshold_strict = 1.6

[rebind-analysis]
rebind_distance_same = 1.0 # Determines rebinds to same particles < parameter
rebind_distance_diff = 5.0 # Determines rebinds to diff particles > parameter
min_time_bound_strict = 5
min_time_bound_constricted = 5
min_time_rebinding_relaxed = 5
min_time_rebinding_strict = 5
min_time_diffusion = 2
min_time_diffusion_subsequent = 2 # minimum time required for subsequent event after diffusion
max_time_rebinding = 200 # after which it will be counted unsuccessful
max_time_constrained = 200 # after which it will be counted unsuccessful
