[path]
# Path to Trackmate csv, all output will be stored in that folder
# csv_path = ""
# Path to segmented masks, .png and .txt files required from Cellpose
# mask_path = ""

#20ms simulation#####

#csv_path = 'D:\\Microscopy\\SMS_BP-master2\\Final_Wt_1exp\\timelapse\\AnalysisRebindCBC_start0_Quality'  # csv from trackmate
#mask_path = 'D:\\Microscopy\\SMS_BP-master2\\Final_Wt_1exp\\seg'  # *.png

#csv_path = 'D:\\Microscopy\\SMS_BP-master\\testScenario7SSGpt_DmFIXREAL\\timelapse\\AnalysisRebindCBC_start0_Quality'  # csv from trackmate
#mask_path = 'D:\\Microscopy\\SMS_BP-master\\testScenario7SSGptWtFIX\\seg'  # *.png

#csv_path = 'D:\\Microscopy\\SMS_BP-master\\test1\\Trackmate_100ms\\timelapse\\AnalysisRebindCBC_start0_Quality'  # csv from trackmate
#mask_path = 'D:\\Microscopy\\SMS_BP-master\\test1\\Trackmate_100ms\\seg'  # *.png

#100ms continious ###################################################################

#csv_path = 'F:\\_Microscopy\\_Rebinding\\Reanalized2023\\DnaQhalotag_bg\\timelapse'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\_Rebinding\\Reanalized2023\\DnaQhalotag_bg\\seg'  # *.png

#csv_path = 'F:\\_Microscopy\\_Rebinding\\Reanalized2023\\20230802_dnaqH\\timelapse'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\_Rebinding\\Reanalized2023\\20230802_dnaqH\\seg'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\20230913_ypetB_haloQ\\Images\\timelapse\\101023\\AnalysisRebindCBC_1010123_start0'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\20230913_ypetB_haloQ\\Images\\seg\\seg101023'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\timelapse\\GOOD_OLD_Quality2point5\\pr212\\AnalysisRebindCBC_11146dia_dog'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\seg_Copy\\pr212'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\timelapse\\GOOD_OLD_Quality2point5\\pr208\\pr208_AnalysisRebindCBC1114_6diam_Dog'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\seg_Copy\\pr208'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\timelapse\\GOOD_OLD_Quality2point5\\pr208n\\AnalysisRebindCBC_11146diam_DOG'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\seg_Copy\\pr208n'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\202301109_TetR_haloQmutnWT\\Images\\COMB\\AnalysisRebindCBC_5quality\\PR212' # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\202301109_TetR_haloQmutnWT\\Images\\seg\\pr212\\100ms\\set1' # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\202301109_TetR_haloQmutnWT\\Images\\COMB\\AnalysisRebindCBC_5quality\\PR212' # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\202301109_TetR_haloQmutnWT\\Images\\seg\\pr212\\100ms\\set1' # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\timelapse\\GOOD_OLD_Quality2point5\\pr212\\AnalysisRebindCBC_11146dia_dog'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\_RUNreb1108_4diameter\\seg_Copy\\pr212'  # *.png


# 20i100ms ##########################################################################
#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\timelapse\\AnalysisRebindCBC_start0_Quality5'
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\seg\\all'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\timelapse\\set3'
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\seg\\set3'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA3\\timelapse\\AnalysisRebindCBC_start0_Quality5'  # csv from trackmate
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA3\\seg\\all'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA3\\timelapse\\Set2'  # csv from trackmate
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA3\\seg\\seg2'  # *.png

csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA7\\timelapse\\AnalysisRebindCBC_start0_Quality5'  # csv from trackmate
mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA7\\seg\\all'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA7\\timelapse\\set1'  # csv from trackmate
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA7\\seg\\set1'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\timelapse\\AnalysisRebindCBC_start0_Quality5'
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\wt\\seg\\all'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA5\\timelapse'  # csv from trackmate
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\MutA5\\seg'  # *.png

#csv_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\SSB113\\timelapse'  # csv from trackmate
#mask_path = 'C:\\Users\\JpRas\\OneDrive\\Escritorio\\RODREBIN\\SSB113\\seg'  # *.png

#csv_path = 'F:\\_Microscopy\\Rawdates\\20240229_od82\\Images\\timelapse\\AnalysisRebindCBC_start0_Quality3_noConFilt'  # csv from trackmate
#mask_path = 'F:\\_Microscopy\\Rawdates\\20240229_od82\\Images\\seg'  # *.png




output_folder_name = '_ColBD_LIFE_FInalest'

[toggle]
use_gap_fixed = true # for rebind-analysis to use gap-fixed
filter_by_binding_prop = true # filter tracks after gap-fixes

[track-sorting]
allowed_gap_max = 10
allowed_track_length_min = 60
allowed_track_length_max = 900
dist_range = 5
allowed_overlap = 30 # allowed total repeated frames in tracks in a cell, eliminate all tracks if exceeds
concurrent_max = 10 # max concurrent frames in *different* tracks in a cell, eliminate the frames if exceeds.

[bound-classification]
distance_threshold = 2.6
distance_threshold_strict = 1.2

[gaps-and-fixes]
min_time_strict = 4
min_time_constrained = 4
min_time_diffusion = 3
max_bound_gapFill = 3
min_prop_binding = 0.08 # for both constricted and strict, filter condition after gap-fixes
max_prop_binding = 0.95 # filter also for all-bound tracks, most-likely dirt

[rebind-analysis]
rebind_distance_same = 1.0 # Determines rebinds to same particles < parameter
rebind_distance_diff = 4.0 # Determines rebinds to diff particles > parameter
min_time_bound_strict = 4
min_time_bound_constrained = 4
min_time_rebinding_relaxed = 0
min_time_rebinding_strict = 10
min_time_diffusion = 0
min_time_diffusion_subsequent = 1 # minimum time required for subsequent event after diffusion
max_time_rebinding = 50 # after which it will be counted unsuccessful
max_time_constrained = 50 # after which it will be counted unsuccessful
