[path]
# Path to Trackmate csv, all output will be stored in that folder
# csv_path = ""
# Path to segmented masks, .png and .txt files required from Cellpose
# mask_path = ""

csv_path = "F:\\MicroscopyTest\\20231210_Dataset\\Fixed_particle\\wt\\Tracking"
mask_path = "F:\\MicroscopyTest\\20231210_Dataset\\Fixed_particle\\wt\\_seg"
output_folder_name = '_ColBD_LIFE'

[toggle]
use_gap_fixed = true # for rebind-analysis to use gap-fixed

[track-sorting]
allowed_gap_max = 20
allowed_track_length_min = 50
allowed_track_length_max = 1500
dist_range = 5
allowed_overlap = 30

[bound-classification]
distance_threshold = 3.0
distance_threshold_strict = 1.6

[gaps-and-fixes]
min_time_strict = 5
min_time_constrained = 5
min_time_diffusion = 5

[rebind-analysis]
rebind_distance_same = 1.0 # Determines rebinds to same particles < parameter
rebind_distance_diff = 5.0 # Determines rebinds to diff particles > parameter
min_time_bound_strict = 5
min_time_bound_constrained = 5
min_time_rebinding_relaxed = 5
min_time_rebinding_strict = 5
min_time_diffusion = 2
min_time_diffusion_subsequent = 2 # minimum time required for subsequent event after diffusion
max_time_rebinding = 200 # after which it will be counted unsuccessful
max_time_constrained = 200 # after which it will be counted unsuccessful
